env:
  browser: true
  es2021: true
extends:
- 'plugin:react/recommended'
- airbnb
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
- react
- '@typescript-eslint'
rules:
  import/extensions: off
  import/no-unresolved: off
  max-len: off
  no-use-before-define: off
  react/jsx-filename-extension:
  - error
  - extensions:
    - tsx
  react/jsx-one-expression-per-line: off
  '@typescript-eslint/no-use-before-define': error
